language: c

addons:
    apt_packages:
        - binutils-mingw-w64
        - gcc-mingw-w64

os:
    - linux

compiler:
    - clang
    - gcc
    - i686-w64-mingw32-gcc
    - x86_64-w64-mingw32-gcc

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="-d --strict-warnings"

matrix:
    include:
        - os: linux
          addons:
              apt:
                  packages:
                      - binutils-aarch64-linux-gnu
                      - gcc-aarch64-linux-gnu
                      - cpp-aarch64-linux-gnu
                      - libc6-dev-arm64-cross
          compiler: aarch64-linux-gnu-gcc
          env: CONFIG_OPTS="--strict-warnings enable-ec_nistp_64_gcc_128"
        - os: linux
          addons:
              apt:
                  packages:
                      - binutils-arm-linux-gnueabihf
                      - gcc-arm-linux-gnueabihf
                      - cpp-arm-linux-gnueabihf
                      - libc6-dev-armhf-cross
          compiler: arm-linux-gnueabihf-gcc
          env: CONFIG_OPTS="--strict-warnings"
    exclude:
        - os: osx
          compiler: i686-w64-mingw32-gcc
        - os: osx
          compiler: x86_64-w64-mingw32-gcc
        - compiler: i686-w64-mingw32-gcc
          env: CONFIG_OPTS="-d --strict-warnings"
        - compiler: x86_64-w64-mingw32-gcc
          env: CONFIG_OPTS="-d --strict-warnings"

before_script:
    - sh .travis-create-release.sh $TRAVIS_OS_NAME
    - tar -xvzf _srcdist.tar.gz
    - cd _srcdist
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw $CONFIG_OPTS;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw64 $CONFIG_OPTS;
      elif [ "$CC" = aarch64-linux-gnu-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          export CONFIG_OPTS="$CONFIG_OPTS -Wno-error=shadow";
          ./Configure linux-aarch64 $CONFIG_OPTS;
      elif [ "$CC" = arm-linux-gnueabi-gcc ] || [ "$CC" = arm-linux-gnueabihf-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          export CONFIG_OPTS="$CONFIG_OPTS -Wno-error=shadow";
          ./Configure linux-armv4 $CONFIG_OPTS;
      else
          if [ "$CC" == gcc ]; then
              export CONFIG_OPTS="$CONFIG_OPTS -Wno-error=shadow";
          fi;
          ./config $CONFIG_OPTS;
      fi
    - cd ..

script:
    - cd _srcdist
    - if make ; then
         echo -e '+\057 MAKE OK';
     else
         echo -e '+\057 MAKE FAILED'; false;
      fi;
    - if [ -z "$CROSS_COMPILE" ]; then
          if make test; then
              echo -e '+\057\057 MAKE TEST OK';
          else
              echo -e '+\057\057 MAKE TEST FAILED'; false;
          fi;
      fi
    - cd ..

notifications:
    email:
        secure: "xeGNgWO7aoaDgRvcZubposqMsj36aU8c6F0oHfw+rUqltCQ14IgYCUwzocmR2O+Pa7B3Cx5VjMfBFHbQaajZsfod8vu7g+aGq/zkjwbhsr/SR4dljJjFJXLGZjIalm9KgP6KInmVDuINfCqP+MHIY5lZkNI7DMcyHDhVc5nSKvCXV7xTDNgmstvh8rB/z51WfHDqGqfBtiuK5FDNxmvYK8OFJ5W94Lu9LDlizcxwK3GAj7arOui7Z5w8bQ6p4seUE3IvJL1Zbj0pZHxvNb6Zeb2Pn8QF1qLlN8YmBktD4aiw0ce4wYRiL87uLgcOxZY7SVXtv2XYFIYWapU/FKjCqa6vK93V/H9eZWEIYNMKnN3wXm2beqVdnKek3OeGJ8v0y7MbSfuLfRtBqbTSNYnpU1Zuo4MQAvHvEPuwCAYkYQajOSRplMH5sULFKptuVqNtOMfjL8jHb8AEoL1acYIk43ydxeYrzzas4fqgCDJ52573/u0RNdF1lkQBLkuM365OB8VRqtpnoxcdEIY/qBc/8TzZ24fxyrs5qdHFcxGSgpN2EP6cJMqpvkemnCNSdhxUqfzm22N7a3O8+4LFSBGOnHto/PwdsvF/01yGYL0LoZTnoO1i6x7AMJPBh+eyDU0ZjGhj/msjmqeb9C8vRqQ+1WjHrIS1iqCD0Czib8tUPD4="
